name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build (Maven)
        run: mvn -B -DskipTests install

      - name: Verify Shaded Jar
        run: |
          ls -l gdx-sqlite-desktop/target || true
          test -f gdx-sqlite-desktop/target/gdx-sqlite-desktop-1.0.0-SNAPSHOT-all.jar

      - name: Attach Artifacts (Desktop shaded)
        uses: actions/upload-artifact@v4
        with:
          name: desktop-shaded-jar
          path: gdx-sqlite-desktop/target/gdx-sqlite-desktop-*-all.jar